avoid compiler error          c:\projects\pythonscript\pythonscript\src\shortcutdlg.cpp(96): error C2429: attribute 'fallthrough' requires compiler flag '/std:c++17' [C:\projects\pythonscript\PythonScript\project\PythonScript2010.vcxproj]