Update intro.rst : correct code in Introduction and Working with Unicode Text
#### in Introduction:
* Removed the line with `editor.pyreplace(...)`: it produces error `AttributeError: 'Editor' object has no attribute 'pyreplace' ` and is not present in PythonScript/doc/scintilla.html
* Corrected the `notepad.runMenuCommand(....)` to use an example of menu items that actually exist in current menu (N++ 8.5.4)
#### in Working with Unicode Text
* Corrected missing 1st argument for `editor.replaceWholeLine`
* For whole script, added a 1st line with encoding
`# -*- coding: utf-8 -*-`
 otherwise, get error :
```
SyntaxError: Non-ASCII character '\xc3' in file C:\Users\Vic\AppData\npp.8.5.4.portable\plugins\Config\PythonScript\scripts\test.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
So I followed that link and added that encoding comment line.

NOTE: needs verification, because when seen with Preview on github, the `*`-s in that line are interpreted as emphasis, instead as showing as-is in the code section